<?php include('header.php'); ?>
<main id="main">
<section id="about" style=" margin-top:50px;">
      <div class="container">

        <header class="section-header">
          <h3>Business Intelligence</h3>
          
        </header>

        <div class="row about-container">

          <div class="col-lg-8 content order-lg-1 order-2">
          <br><br><br>
            <p>
              By leveraging a range of visualization tools and big data technologies our experts offers best results across the entire data cycle. We analyzing and identifying patterns, relationships and regularities in data to provide insights about the dynamics of data that could be used to power up the business intelligence.
            </p>
            <p>
         Our aim to prepare clients for facing market challenges includes unwieldy data supply chains, interoperable technologies and data architecture. We create modern data supply chain to help businesses in managing, moving & mobilize large data spread throughout the organization.
            </p>

          </div>

          <div class="col-lg-4 background order-lg-2 order-1 wow fadeInUp">
             <img src="img/bi_sol_img.png" class="img-fluid" alt="">
          </div>
        </div>

        <div class="row" style="margin-top:50px;">

          <div class="col-md-6 col-lg-5 offset-lg-1 wow bounceInUp" data-wow-duration="1.4s">
            <div class="box">
             
              <h4 class="title"><a href="#">Enterprise Data</a></h4>
              <p class="description">Implement transactional ERP data, CRM system and different variety of semi-structured & unstructured data present in the content repositories.</p>
            </div>
          </div>
          <div class="col-md-6 col-lg-5 wow bounceInUp" data-wow-duration="1.4s">
            <div class="box">
             
              <h4 class="title"><a href="#">Machine Data</a></h4>
              <p class="description">End-to-end transaction visibility to log files and other machine-generated data for complete insight of IT infrastructure.</p>
            </div>
          </div>

          <div class="col-md-6 col-lg-5 offset-lg-1 wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="box">
              
              <h4 class="title"><a href="#">Sensor-Generated Data</a></h4>
              <p class="description">Data accumulated from smart devices, control systems, connected appliances, industrial equipment and any IoT device.</p>
            </div>
          </div>
          <div class="col-md-6 col-lg-5 wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="box">
              
              <h4 class="title"><a href="#">Social Data</a></h4>
              <p class="description">Data has been generated by people in digital world, social media platforms and location based services.</p>
            </div>
          </div>

          
          

        </div>

        
      </div>
    </section>
    
    
    
    <section id="why-us" class="wow fadeIn">
      <div class="container">
        <header class="section-header">
          <h3>Big Data</h3>
          <p>Discover and drive business value by providing innovative big data solutions for various industries. Implement big data technology to deliver & resolving complex big data challenges and get best outcomes.</p>
        </header>

        <div class="row row-eq-height justify-content-center">

          <div class="col-lg-3 mb-3">
            <div class="card wow bounceInUp">
               
              <div class="card-body">
                <h5 class="card-title">Big Data Consulting</h5>
                <p class="card-text">Big data consulting to become relevant, competitive & deriving practical results.</p>
                
              </div>
            </div>
          </div>
          
          <div class="col-lg-3 mb-3">
            <div class="card wow bounceInUp">
                
              <div class="card-body">
                <h5 class="card-title">Data Science</h5>
                <p class="card-text">Experts of BI technologies for retrieving valuable data from raw data.</p>
               
              </div>
            </div>
          </div>

          <div class="col-lg-3 mb-3">
            <div class="card wow bounceInUp">
               
              <div class="card-body">
                <h5 class="card-title">Big Data Solution</h5>
                <p class="card-text">Analyze and provide interactive big data solution for better insight.</p>
                
              </div>
            </div>
          </div>

          <div class="col-lg-3 mb-3">
            <div class="card wow bounceInUp">
                
              <div class="card-body">
                <h5 class="card-title">Big Data Implementation</h5>
                <p class="card-text">Analyze structured and unstructured data for efficient data management & implementation.</p>
               
              </div>
            </div>
          </div>

        </div>

        

      </div>
    </section>
    
    <section id="about">
      <div class="container">

        <header class="section-header">
          <h3>Explore Business Intelligence to Work Smarter</h3>
          <p>Our operational business intelligence solutions utilize real time data integration that support transactional and sub transactional information for all business verticals.</p>
          
        </header>

        <div class="row about-container">

          <div class="col-lg-8 content order-lg-1 order-2">
          
          
          <div class=" wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="box">
              
              <h4 class="title"><a href="#">BI Platform Services</a></h4>
              <p class="description">Highly scalable and secure cloud analytics BI platform that powers the entire data for insightful delivery.</p>
            </div>
          </div>
          
          <div class=" wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="box">
              
              <h4 class="title"><a href="#">Assessments, Roadmaps & Strategy</a></h4>
              <p class="description">Implementing the right IoT applications and architecture with scalable infrastructure to keep you stay strategic.</p>
            </div>
          </div>
          <div class=" wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="box">
              
              <h4 class="title"><a href="#">Enterprise Reporting Solutions</a></h4>
              <p class="description">Rich interactive reports and dashboard that allow the users interact with it inside and outside of the enterprise.</p>
            </div>
          </div>
          <div class=" wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="box">
              
              <h4 class="title"><a href="#">Data Visualizations</a></h4>
              <p class="description">Get instant clarity to improve business operations and ROI with stunningly visual analysis and self-discovery.</p>
            </div>
          </div>
          
          
          
          
          
           

            

            

            

          </div>

          <div class="col-lg-4 background order-lg-2 order-1 wow fadeInUp">
            <img src="img/bi_sol_img.png" class="img-fluid" alt="">
          </div>
        </div>

        

        

      </div>
    </section>
    
    
    
    
    
    
    
    
    
    
    
    
    
    </main>


<?php include('footer.php'); ?>